name: 'Release'

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_location: target/release/aiosaber-beatsaver-cache
            asset_name: aiosaber-beatsaver-cache-linux
          - os: windows-latest
            asset_location: target/release/aiosaber-beatsaver-cache.exe
            asset_name: aiosaber-beatsaver-cache-win.exe
          - os: macos-latest
            asset_location: target/release/aiosaber-beatsaver-cache
            asset_name: aiosaber-beatsaver-cache-mac

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: cargo build --release --locked
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_location }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
